import ROOT as r
from ROOT import gDirectory, gROOT, gStyle, gPad
import optparse
import os
from include.plotTools import *

if __name__ == "__main__":

    r.gROOT.LoadMacro('include/tdrstyle.C')
    r.gROOT.SetBatch(1)
    r.setTDRStyle()
    r.gStyle.SetPadRightMargin(0.12)

    filenamePU70 = '/eos/user/f/fernance/MuonPU/Mu_FlatPt-1to1000-gun/muonAnalysis-PU70/230126_173748/output.root'
    filenamePU60 = '/eos/user/f/fernance/MuonPU/Mu_FlatPt-1to1000-gun/muonAnalysis-PU60/230126_173535/output.root'

    ## Plot histograms
    h_mu_pt_70 = getObject(filenamePU70, 'h_mu_pt')
    h_mu_eta_70 = getObject(filenamePU70, 'h_mu_eta')
    h_gen_pt_70 = getObject(filenamePU70, 'h_gen_pt')
    h_gen_eta_70 = getObject(filenamePU70, 'h_gen_eta')
    h_glb_normalizedChi2_70 = getObject(filenamePU70, 'h_glb_normalizedChi2')
    h_glb_dxy_70 = getObject(filenamePU70, 'h_glb_dxy')
    h_glb_dz_70 = getObject(filenamePU70, 'h_glb_dz')
    h_glb_numberOfValidMuonHits_70 = getObject(filenamePU70, 'h_glb_numberOfValidMuonHits')
    h_glb_numberOfMatchedStations_70 = getObject(filenamePU70, 'h_glb_numberOfMatchedStations')
    h_glb_trackerLayers_70 = getObject(filenamePU70, 'h_glb_trackerLayers')
    h_glb_pixelLayers_70 = getObject(filenamePU70, 'h_glb_pixelLayers')
    h_trk_dxy_70 = getObject(filenamePU70, 'h_trk_dxy')
    h_trk_dz_70 = getObject(filenamePU70, 'h_trk_dz')
    h_trk_trackerLayers_70 = getObject(filenamePU70, 'h_trk_trackerLayers')
    h_trk_pixelLayers_70 = getObject(filenamePU70, 'h_trk_pixelLayers')
    
    e_mu_pt_70 = getObject(filenamePU70, 'e_mu_pt')
    e_mu_eta_70 = getObject(filenamePU70, 'e_mu_eta')
    e_glb_pt_TightID_70 = getObject(filenamePU70, 'e_glb_pt_TightID')
    e_glb_eta_TightID_70 = getObject(filenamePU70, 'e_glb_eta_TightID')
    e_trk_pt_SoftID_70 = getObject(filenamePU70, 'e_trk_pt_SoftID')
    e_trk_eta_SoftID_70 = getObject(filenamePU70, 'e_trk_eta_SoftID')
    e_glb_pt_PFIsoLoose_70 = getObject(filenamePU70, 'e_glb_pt_PFIsoLoose')
    e_glb_pt_PFIsoMedium_70 = getObject(filenamePU70, 'e_glb_pt_PFIsoMedium')
    e_glb_pt_PFIsoTight_70 = getObject(filenamePU70, 'e_glb_pt_PFIsoTight')
    e_glb_eta_PFIsoLoose_70 = getObject(filenamePU70, 'e_glb_eta_PFIsoLoose')
    e_glb_eta_PFIsoMedium_70 = getObject(filenamePU70, 'e_glb_eta_PFIsoMedium')
    e_glb_eta_PFIsoTight_70 = getObject(filenamePU70, 'e_glb_eta_PFIsoTight')


    h_mu_pt_60 = getObject(filenamePU60, 'h_mu_pt')
    h_mu_eta_60 = getObject(filenamePU60, 'h_mu_eta')
    h_gen_pt_60 = getObject(filenamePU60, 'h_gen_pt')
    h_gen_eta_60 = getObject(filenamePU60, 'h_gen_eta')
    h_glb_normalizedChi2_60 = getObject(filenamePU60, 'h_glb_normalizedChi2')
    h_glb_dxy_60 = getObject(filenamePU60, 'h_glb_dxy')
    h_glb_dz_60 = getObject(filenamePU60, 'h_glb_dz')
    h_glb_numberOfValidMuonHits_60 = getObject(filenamePU60, 'h_glb_numberOfValidMuonHits')
    h_glb_numberOfMatchedStations_60 = getObject(filenamePU60, 'h_glb_numberOfMatchedStations')
    h_glb_trackerLayers_60 = getObject(filenamePU60, 'h_glb_trackerLayers')
    h_glb_pixelLayers_60 = getObject(filenamePU60, 'h_glb_pixelLayers')
    h_trk_dxy_60 = getObject(filenamePU60, 'h_trk_dxy')
    h_trk_dz_60 = getObject(filenamePU60, 'h_trk_dz')
    h_trk_trackerLayers_60 = getObject(filenamePU60, 'h_trk_trackerLayers')
    h_trk_pixelLayers_60 = getObject(filenamePU60, 'h_trk_pixelLayers')

    e_mu_pt_60 = getObject(filenamePU60, 'e_mu_pt')
    e_mu_eta_60 = getObject(filenamePU60, 'e_mu_eta')
    e_glb_pt_TightID_60 = getObject(filenamePU60, 'e_glb_pt_TightID')
    e_glb_eta_TightID_60 = getObject(filenamePU60, 'e_glb_eta_TightID')
    e_trk_pt_SoftID_60 = getObject(filenamePU60, 'e_trk_pt_SoftID')
    e_trk_eta_SoftID_60 = getObject(filenamePU60, 'e_trk_eta_SoftID')
    e_glb_pt_PFIsoLoose_60 = getObject(filenamePU60, 'e_glb_pt_PFIsoLoose')
    e_glb_pt_PFIsoMedium_60 = getObject(filenamePU60, 'e_glb_pt_PFIsoMedium')
    e_glb_pt_PFIsoTight_60 = getObject(filenamePU60, 'e_glb_pt_PFIsoTight')
    e_glb_eta_PFIsoLoose_60 = getObject(filenamePU60, 'e_glb_eta_PFIsoLoose')
    e_glb_eta_PFIsoMedium_60 = getObject(filenamePU60, 'e_glb_eta_PFIsoMedium')
    e_glb_eta_PFIsoTight_60 = getObject(filenamePU60, 'e_glb_eta_PFIsoTight')

    weight = h_gen_pt_60.GetEntries()/h_gen_pt_70.GetEntries()   
    weight_gbl = h_glb_dxy_60.GetEntries()/h_glb_dxy_70.GetEntries()   
    weight_trk = h_trk_dxy_60.GetEntries()/h_trk_dxy_70.GetEntries()   
    h_mu_pt_70.Scale(weight)
    h_mu_eta_70.Scale(weight)
    h_gen_pt_70.Scale(weight)
    h_gen_eta_70.Scale(weight)
    h_glb_dxy_70.Scale(weight_gbl)
    h_glb_dz_70.Scale(weight_gbl)
    h_glb_normalizedChi2_70.Scale(weight_gbl)
    h_glb_numberOfValidMuonHits_70.Scale(weight_gbl)
    h_glb_numberOfMatchedStations_70.Scale(weight_gbl)
    h_glb_trackerLayers_70.Scale(weight_gbl)
    h_glb_pixelLayers_70.Scale(weight_gbl)
    h_trk_dxy_70.Scale(weight_gbl)
    h_trk_dz_70.Scale(weight_gbl)
    h_trk_trackerLayers_70.Scale(weight_gbl)
    h_trk_pixelLayers_70.Scale(weight_gbl)

    """
    plotValidation('h_mu_pt', h_mu_pt_70, h_mu_pt_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "All reco muons (Norm. to num. of gen muons)", ylog = True)
    plotValidation('h_mu_eta', h_mu_eta_70, h_mu_eta_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "All reco muons (Norm. to num. of gen muons)", ylog = False)
    plotValidation('h_glb_dxy', h_glb_dxy_70, h_glb_dxy_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched GLB (Norm. to num. of Gen-matched GLB)", ylog = False)
    plotValidation('h_glb_dz', h_glb_dz_70, h_glb_dz_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched GLB (Norm. to num. of Gen-matched GLB)", ylog = False)
    plotValidation('h_glb_trackerLayers', h_glb_trackerLayers_70, h_glb_trackerLayers_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched GLB (Norm. to num. of Gen-matched GLB)", ylog = True)
    plotValidation('h_glb_pixelLayers', h_glb_pixelLayers_70, h_glb_pixelLayers_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched GLB (Norm. to num. of Gen-matched GLB)", ylog = True)
    plotValidation('h_trk_dxy', h_trk_dxy_70, h_trk_dxy_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched TRK (Norm. to num. of Gen-matched TRK)", ylog = False)
    plotValidation('h_trk_dz', h_trk_dz_70, h_trk_dz_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched TRK (Norm. to num. of Gen-matched TRK)", ylog = False)
    plotValidation('h_trk_trackerLayers', h_trk_trackerLayers_70, h_trk_trackerLayers_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched TRK (Norm. to num. of Gen-matched TRK)", ylog = True)
    plotValidation('h_trk_pixelLayers', h_trk_pixelLayers_70, h_trk_pixelLayers_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched TRK (Norm. to num. of Gen-matched TRK)", ylog = True)
    plotValidation('h_glb_numberOfValidMuonHits', h_glb_numberOfValidMuonHits_70, h_glb_numberOfValidMuonHits_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched GLB (Norm. to num. of Gen-matched GLB)", ylog = True)
    plotValidation('h_glb_numberOfMatchedStations', h_glb_numberOfMatchedStations_70, h_glb_numberOfMatchedStations_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched GLB (Norm. to num. of Gen-matched GLB)", ylog = True)
    plotValidation('h_glb_normalizedChi2', h_glb_normalizedChi2_70, h_glb_normalizedChi2_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Gen-matched GLB (Norm. to num. of Gen-matched GLB)", ylog = True)
    #plotValidation('h_gen_pt_w', h_gen_pt_70, h_gen_pt_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Generated muons (Norm. to num. of gen muons)", ylog = False)
    #plotValidation('h_gen_eta_w', h_gen_eta_70, h_gen_eta_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Generated muons (Norm. to num. of gen muons)", ylog = False)
    """
    plotEfficiency('e_mu_pt', e_mu_pt_70, e_mu_pt_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Reconstructed / Generated", ylog = False)
    plotEfficiency('e_mu_eta', e_mu_eta_70, e_mu_eta_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "Reconstructed / Generated", ylog = False)
    plotEfficiency('e_glb_pt_TightID', e_glb_pt_TightID_70, e_glb_pt_TightID_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "TightID / Gen-matched GLB", ylog = False)
    plotEfficiency('e_glb_eta_TightID', e_glb_eta_TightID_70, e_glb_eta_TightID_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "TightID / Gen-matched GLB", ylog = False)
    plotEfficiency('e_glb_pt_PFIsoLoose', e_glb_pt_PFIsoLoose_70, e_glb_pt_PFIsoLoose_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "PFIsoLoose / Gen-matched GLB", ylog = False)
    plotEfficiency('e_glb_eta_PFIsoLoose', e_glb_eta_PFIsoLoose_70, e_glb_eta_PFIsoLoose_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "PFIsoLoose / Gen-matched GLB", ylog = False)
    plotEfficiency('e_glb_pt_PFIsoMedium', e_glb_pt_PFIsoMedium_70, e_glb_pt_PFIsoMedium_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "PFIsoMedium / Gen-matched GLB", ylog = False)
    plotEfficiency('e_glb_eta_PFIsoMedium', e_glb_eta_PFIsoMedium_70, e_glb_eta_PFIsoMedium_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "PFIsoMedium / Gen-matched GLB", ylog = False)
    plotEfficiency('e_glb_pt_PFIsoTight', e_glb_pt_PFIsoTight_70, e_glb_pt_PFIsoTight_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "PFIsoTight / Gen-matched GLB", ylog = False)
    plotEfficiency('e_glb_eta_PFIsoTight', e_glb_eta_PFIsoTight_70, e_glb_eta_PFIsoTight_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "PFIsoTight / Gen-matched GLB", ylog = False)
    plotEfficiency('e_trk_pt_SoftID', e_trk_pt_SoftID_70, e_trk_pt_SoftID_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "SoftID / Gen-matched TRK", ylog = False)
    plotEfficiency('e_trk_eta_SoftID', e_trk_eta_SoftID_70, e_trk_eta_SoftID_60, '/eos/user/f/fernance/www/MuonPOG/MuonPerformancePU/', 'Poisson70KeepRAW', 'Poisson60KeepRAW', "SoftID / Gen-matched TRK", ylog = False)
